version: '3'

services:
  raft-1: &raft
    image: raft
    build:
      context: .
    network_mode: host
    command:
    - ./server.py
    - --name
    - raft-1
    - --addr
    - "0.0.0.0"
    - --port
    - "2468"

  raft-2:
    <<: *raft
    command:
    - ./server.py
    - --name
    - raft-2
    - --addr
    - "0.0.0.0"
    - --port
    - "2469"

  raft-3:
    <<: *raft
    command:
    - ./server.py
    - --name
    - raft-1
    - --addr
    - "0.0.0.0"
    - --port
    - "2470"
